<?php

namespace AppBundle\Repository;

/**
 * actorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class actorRepository extends \Doctrine\ORM\EntityRepository
{
}
