<?php

namespace AppBundle\Repository;

/**
 * actor_favoritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class actor_favoritoRepository extends \Doctrine\ORM\EntityRepository
{
}
