<?php

namespace AppBundle\Repository;

/**
 * imagenesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imagenesRepository extends \Doctrine\ORM\EntityRepository
{
}
