<?php

namespace AppBundle\Repository;

/**
 * pelicula_favoritaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pelicula_favoritaRepository extends \Doctrine\ORM\EntityRepository
{
}
