<?php

namespace AppBundle\Repository;

/**
 * peliculaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class peliculaRepository extends \Doctrine\ORM\EntityRepository
{
}
