<?php

namespace AppBundle\Repository;

/**
 * servidorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class servidorRepository extends \Doctrine\ORM\EntityRepository
{
}
